from .main_routes import *
from .user import *
from .time_packages import *
from .admin import *
from .computers import *
from .payments import *
from .coupons import *
from .friends import *
from .bonus_routes import *
from .loyalty_routes import *